import Head from 'next/head'
import Contingency from '../component/pages/contingencyPlan'
import styles from '../styles/Home.module.css'


export default function ContingencyPlan() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Contingency/>
    </div>
  )
}
