import Head from 'next/head';
import Contact from '../component/pages/contact_us';

export default function ContactUsPage() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Contact/>
    </div>
  )
}
