import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Parenting from '../component/pages/parenting'

export default function ParentingPage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Parenting />
    </div>
  )
}
